package pl.edu.kosttek.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Mon Aug 27 21:27:56 CEST 2012
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://webservice.kosttek.edu.pl/", name = "GetConferences")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface GetConferences {

    @WebResult(name = "return", targetNamespace = "http://webservice.kosttek.edu.pl/", partName = "return")
    @WebMethod
    public java.lang.String putConferenceToDB(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0,
        @WebParam(partName = "arg1", name = "arg1")
        java.lang.String arg1,
        @WebParam(partName = "arg2", name = "arg2")
        java.lang.String arg2,
        @WebParam(partName = "arg3", name = "arg3")
        java.lang.String arg3
    );

    @WebResult(name = "return", targetNamespace = "http://webservice.kosttek.edu.pl/", partName = "return")
    @WebMethod
    public java.lang.String echoTest();

    @WebResult(name = "return", targetNamespace = "http://webservice.kosttek.edu.pl/", partName = "return")
    @WebMethod
    public java.lang.String removeConference(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "http://webservice.kosttek.edu.pl/", partName = "return")
    @WebMethod
    public ConferenceArray getConferences();
}
