
/*
 * 
 */

package pl.edu.kosttek.webservice.schedule;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Thu Aug 23 23:59:13 CEST 2012
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "GetSchedulesBeanService", 
                  wsdlLocation = "http://localhost:8080/ConferenceEJB/GetSchedulesBean?wsdl",
                  targetNamespace = "http://webservice.kosttek.edu.pl/") 
public class GetSchedulesBeanService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.kosttek.edu.pl/", "GetSchedulesBeanService");
    public final static QName GetSchedulesBeanPort = new QName("http://webservice.kosttek.edu.pl/", "GetSchedulesBeanPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/ConferenceEJB/GetSchedulesBean?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8080/ConferenceEJB/GetSchedulesBean?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public GetSchedulesBeanService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GetSchedulesBeanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetSchedulesBeanService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public GetSchedulesBeanService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public GetSchedulesBeanService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public GetSchedulesBeanService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns GetSchedules
     */
    @WebEndpoint(name = "GetSchedulesBeanPort")
    public GetSchedules getGetSchedulesBeanPort() {
        return super.getPort(GetSchedulesBeanPort, GetSchedules.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetSchedules
     */
    @WebEndpoint(name = "GetSchedulesBeanPort")
    public GetSchedules getGetSchedulesBeanPort(WebServiceFeature... features) {
        return super.getPort(GetSchedulesBeanPort, GetSchedules.class, features);
    }

}
